---
- name: Install PHP and dependancies
  become: yes
  apt: name={{ packages }} state=present update_cache=yes cache_valid_time=3600
  vars:
    packages:
      - php7.2
      - php-fpm
      - php-cli
      - php-mysql
      - php-mbstring
      - php-opcache
      - php-xml

- name: Add default settings for php
  template:
    src: "php.ini.j2"
    #dest: /etc/php.ini
    dest: /etc/php/{{ php_version }}/fpm/php.ini

- name: Add default settings for php-cli
  template:
    src: "php.ini.j2"
    #dest: /etc/php.ini
    dest: /etc/php/{{ php_version }}/cli/php.ini

# - name: Default settings for php-fpm
#   lineinfile:
#     dest: /etc/php/7.2/fpm/pool.d/www.conf
#     regexp: '^www-data\s+'
#     line: nginx

- name: Make www.conf for php-fpm
  template:
    src: "www.conf.j2"
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
  notify: Restart php{{ php_version }}-fpm

# - name: Disable default pool
#   command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disable creates=/etc/php-fpm.d/www.disabled

# - name: PHP | Add php-7.2 PPA
#   apt_repository: repo='ppa:ondrej/php' state=present update_cache=yes
#   become: yes
#   tags: php