---
# Vhosts
- name: Make conf file for entrypoint each sites
  template:
    src: "main.conf.j2"
    dest: /etc/nginx/conf.d/{{ item.domain }}.conf
  with_items:
    - "{{ nginx_sites }}"
  notify: Reload Nginx

- name: Create document dir
  file: path={{ item.document_dir }} state=directory
  with_items:
    - "{{ nginx_sites }}"

- name: Create document root
  file: path={{ item.document_root }} state=directory
  with_items:
    - "{{ nginx_sites }}"